spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:6432/sandbox
    username: admin
    password: admin
server:
  port: 8081
logging:
  level:
    org.springframework.security: TRACE


